apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "log-generator.fullname" . }}
  labels:
    app: {{ include "log-generator.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "log-generator.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "log-generator.name" . }}
    spec:
      containers:
      - name: log-generator
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/bin/sh"]
        args:
          - "-c"
          - |
            while true; do
              echo "Log entry at $(date)" | tee /dev/stdout;
              sleep 5;
            done

