apiVersion: v1
kind: Service
metadata:
  name: {{ include "log-generator.fullname" . }}
spec:
  selector:
    app: {{ include "log-generator.name" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

